blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/fluxscape/fluxscape-docs/discussions/categories/feature-requests
    about: Request a new feature or example.
